module.exports = [
  // {
  //   SKU: '2.9x4.6_29384_27665',
  //   Name: `2'9x4'6`,
  //   Price: 148.56,
  //   LongDescription: '100% Tibetan Wool',
  //   ShortDescription: '100 Knot',
  //   Weight: 8,
  //   Width: 2.9,
  //   Height: 4.6,
  //   Qty: 1,
  // },
  // {
  //   SKU: '2.9x4.11_29383_1712',
  //   Name: `2'9x4'11`,
  //   Price: 162.52,
  //   LongDescription: '100% Tibetan Wool',
  //   ShortDescription: '60 Knot',
  //   Weight: 8,
  //   Width: 2.9,
  //   Height: 4.11,
  //   Qty: 1,
  // },
  // {
  //   SKU: '1.11x3_31720_2830',
  //   Name: `1'11x3 Tiger's Eye`,
  //   Price: 138,
  //   LongDescription: '100% Tibetan Wool',
  //   ShortDescription: '80 Knot',
  //   Weight: 5,
  //   Width: 1.11,
  //   Height: 3,
  //   Qty: 1,
  // },
  // {
  //   SKU: '2.11x4.9_32428_3187',
  //   Name: `2'11x4'9`,
  //   Price: 249.30,
  //   LongDescription: '100% Tibetan Wool',
  //   ShortDescription: '80 Knot',
  //   Weight: 5,
  //   Width: 2.11,
  //   Height: 4.9,
  //   Qty: 1,
  // },
  {
    SKU: "2.11x4.10_29388_27667",
    "Name": "",
    "Price": "$6/sf = $84.60",
    "Long Description": "Tibetan Wool",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "8",
    "Colors": ""
  },
  {
    SKU: "2.11x4.11_29359_27569",
    "Name": "",
    "Price": "$6/sf = $86.04",
    "Long Description": "Tibetan Wool",
    "Short Description": "60 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "8",
    "Colors": ""
  },
  {
    SKU: "2.11x4.11_29361_27568",
    "Name": "",
    "Price": "$6/sf = $86.04",
    "Long Description": "Tibetan Wool",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "8",
    "Colors": ""
  },
  {
    SKU: "2x2.10_27949_26045",
    "Name": "",
    "Price": "$7/sf = $39.69",
    "Long Description": "Tibetan Wool",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "4",
    "Colors": ""
  },
  {
    SKU: "2x2.10_32205_3029",
    "Name": "",
    "Price": "$5/sf = $28.35",
    "Long Description": "Tibetan Wool",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "5",
    "Colors": ""
  },
  {
    SKU: "2x2.11_31708_2628",
    "Name": "Ric Rac",
    "Price": "$10/sf = $58.30",
    "Long Description": "Tibetan Wool",
    "Short Description": "60 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "6",
    "Colors": ""
  },
  {
    SKU: "2x2.11_32202_3052",
    "Name": "",
    "Price": "$5/sf = 29.15",
    "Long Description": "Tibetan Wool",
    "Short Description": "60 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "6",
    "Colors": ""
  },
  {
    SKU: "2x2.11_32220_3032",
    "Name": "",
    "Price": "$11/sf = $64.13",
    "Long Description": "Tibetan Wool w/Silk",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "5",
    "Colors": ""
  },
  {
    SKU: "2x2.11_32488_3316",
    "Name": "",
    "Price": "$11/sf = $64.13",
    "Long Description": "Tibetan Wool w/Silk",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "5",
    "Colors": ""
  },
  {
    SKU: "2x2.11_32690_29435",
    "Name": "",
    "Price": "$12/sf = $69.96",
    "Long Description": "Tibetan Wool w/Silk",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "4",
    "Colors": ""
  },
  {
    SKU: "2x3_4_3773E",
    "Name": "",
    "Price": "$18/sf = $108",
    "Long Description": "New Zealand Wool",
    "Short Description": "Persian Knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "6",
    "Colors": ""
  },
  {
    SKU: "2x3_16961_16475",
    "Name": "Kelp",
    "Price": "$10/sf = $60.00",
    "Long Description": "Tibetan Wool",
    "Short Description": "60 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "6",
    "Colors": ""
  },
  {
    SKU: "2x3_30038_27833",
    "Name": "Retro",
    "Price": "$13/sf = $78",
    "Long Description": "Tibetan Wool w/Silk",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "4",
    "Colors": ""
  },
  {
    SKU: "2x3_31919_29173",
    "Name": "Diamondback",
    "Price": "$14/sf = $84",
    "Long Description": "Tibetan Wool w/Silk",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "4",
    "Colors": ""
  },
  {
    SKU: "2x3_32196_3074",
    "Name": "",
    "Price": "$9/sf = $54",
    "Long Description": "Tibetan Wool",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "5",
    "Colors": ""
  },
  {
    SKU: "2x3_32197_29256",
    "Name": "",
    "Price": "$11/sf = $66",
    "Long Description": "Tibetan Wool",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "4",
    "Colors": ""
  },
  {
    SKU: "2x3_32198_3044",
    "Name": "",
    "Price": "$9/sf = $54",
    "Long Description": "Tibetan Wool",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "5",
    "Colors": ""
  },
  {
    SKU: "2x3_32199_29257",
    "Name": "",
    "Price": "$10/sf = $60",
    "Long Description": "Tibetan Wool",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "4",
    "Colors": ""
  },
  {
    SKU: "2x3_32201_3049",
    "Name": "",
    "Price": "$6/sf = $36",
    "Long Description": "Tibetan Wool",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "5",
    "Colors": ""
  },
  {
    SKU: "2x3_32206_3046",
    "Name": "",
    "Price": "$6/sf = $36",
    "Long Description": "Tibetan Wool",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "5",
    "Colors": ""
  },
  {
    SKU: "2x3_32209_3075",
    "Name": "",
    "Price": "$9/sf = $54",
    "Long Description": "Tibetan Wool",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "5",
    "Colors": ""
  },
  {
    SKU: "2x3_32210_3104",
    "Name": "",
    "Price": "$8/sf = $54",
    "Long Description": "Tibetan Wool",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "5",
    "Colors": ""
  },
  {
    SKU: "2x3_32211_3048",
    "Name": "",
    "Price": "$11/sf = $66",
    "Long Description": "Tibetan Wool w/Silk",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "5",
    "Colors": ""
  },
  {
    SKU: "2x3_32213_3028",
    "Name": "",
    "Price": "$9/sf = $54",
    "Long Description": "Tibetan Wool",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "5",
    "Colors": ""
  },
  {
    SKU: "2x3_32214_3031",
    "Name": "",
    "Price": "$9/sf = $54",
    "Long Description": "Tibetan Wool",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "5",
    "Colors": ""
  },
  {
    SKU: "2x3_32215_3047",
    "Name": "",
    "Price": "$9/sf = $54",
    "Long Description": "Tibetan Wool",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "5",
    "Colors": ""
  },
  {
    SKU: "2x3_32218_3042",
    "Name": "",
    "Price": "$9/sf = $54",
    "Long Description": "Tibetan Wool",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "5",
    "Colors": ""
  },
  {
    SKU: "2x3_32219_29255",
    "Name": "",
    "Price": "$10/sf = $60",
    "Long Description": "Tibetan Wool",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "4",
    "Colors": ""
  },
  {
    SKU: "2x3_32222_3076",
    "Name": "",
    "Price": "$9/sf = $54",
    "Long Description": "Tibetan Wool",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "5",
    "Colors": ""
  },
  {
    SKU: "2x3_32261_3326",
    "Name": "",
    "Price": "$10/sf = $60",
    "Long Description": "Tibetan Wool",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "5",
    "Colors": ""
  },
  {
    SKU: "2x3_32483_3341",
    "Name": "",
    "Price": "$9/sf = $54",
    "Long Description": "Tibetan Wool",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "5",
    "Colors": ""
  },
  {
    SKU: "2x3_32484_3314",
    "Name": "",
    "Price": "$9/sf = $54",
    "Long Description": "Tibetan Wool",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "5",
    "Colors": ""
  },
  {
    SKU: "2x3_32485_3342",
    "Name": "",
    "Price": "$9/sf = $54",
    "Long Description": "Tibetan Wool",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "5",
    "Colors": ""
  },
  {
    SKU: "2x3_32486_3340",
    "Name": "",
    "Price": "$9/sf = $54",
    "Long Description": "Tibetan Wool",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "5",
    "Colors": ""
  },
  {
    SKU: "2x3_32507_3424",
    "Name": "",
    "Price": "$9/sf = $54",
    "Long Description": "Tibetan Wool",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "5",
    "Colors": ""
  },
  {
    SKU: "2x3_32508_3423",
    "Name": "",
    "Price": "$9/sf = $54",
    "Long Description": "Tibetan Wool",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "5",
    "Colors": ""
  },
  {
    SKU: "2x3_32689_3425",
    "Name": "",
    "Price": "$9/sf = $54",
    "Long Description": "Tibetan Wool",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "5",
    "Colors": ""
  },
  {
    SKU: "2x3_H_Olive",
    "Name": "",
    "Price": "$8",
    "Long Description": "Hemp",
    "Short Description": "Hemp Rug",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "5",
    "Colors": ""
  },
  {
    SKU: "2x3_H_Walnut",
    "Name": "",
    "Price": "$8",
    "Long Description": "Hemp",
    "Short Description": "Hemp Rug",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "5",
    "Colors": ""
  },
  {
    SKU: "2x3.1_30366_28307",
    "Name": "Tibetan Clouds",
    "Price": "$12/sf = $74.04",
    "Long Description": "Tibetan Wool",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "5",
    "Colors": ""
  },
  {
    SKU: "2x3.1_32207_3107",
    "Name": "",
    "Price": "$5/sf = $30.85",
    "Long Description": "Tibetan Wool",
    "Short Description": "60 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "6",
    "Colors": ""
  },
  {
    SKU: "2x3.1_32216_3045",
    "Name": "",
    "Price": "$9/sf = $55.53",
    "Long Description": "Tibetan Wool",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "5",
    "Colors": ""
  },
  {
    SKU: "2x3.1_32487_3327",
    "Name": "",
    "Price": "$9/sf = $55.53",
    "Long Description": "Tibetan Wool",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "5",
    "Colors": ""
  },
  {
    SKU: "2x3.1_S_881_165",
    "Name": "Kazak 9",
    "Price": "$6/sf = $36",
    "Long Description": "New Zealand Wool",
    "Short Description": "Soumak (Flatweave)",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "5",
    "Colors": ""
  },
  {
    SKU: "2x3.1_S_2196_150",
    "Name": "Suzani 1",
    "Price": "$7/sf = $42",
    "Long Description": "New Zealand Wool",
    "Short Description": "Soumak (Flatweave)",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "5",
    "Colors": ""
  },
  {
    SKU: "2x3.1_S_2748_292",
    "Name": "Suzani 9",
    "Price": "$7/sf = $42",
    "Long Description": "New Zealand Wool",
    "Short Description": "Soumak (Flatweave)",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "5",
    "Colors": ""
  },
  {
    SKU: "2x3.2_32525_3518",
    "Name": "",
    "Price": "$9/sf = $56.97",
    "Long Description": "Tibetan Wool",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "5",
    "Colors": ""
  },
  {
    SKU: "2x3.3_S_1603_874",
    "Name": "Suzani 11",
    "Price": "$7/sf = $42",
    "Long Description": "New Zealand Wool",
    "Short Description": "Soumak (Flatweave)",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "5",
    "Colors": ""
  },
  {
    SKU: "2x4_32989_3830",
    "Name": "",
    "Price": "$12/sf = $96",
    "Long Description": "Tibetan Wool w/Silk",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "7",
    "Colors": ""
  },
  {
    SKU: "3.1x4.9_32427_2525",
    "Name": "",
    "Price": "$9/sf = $131.85",
    "Long Description": "Tibetan Wool",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "12",
    "Colors": ""
  },
  {
    SKU: "3.1x4.10_29983_27932",
    "Name": "",
    "Price": "$9/sf = $134.10",
    "Long Description": "Tibetan Wool",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "12",
    "Colors": ""
  },
  {
    SKU: "3.1x4.10_29988_1790",
    "Name": "",
    "Price": "$7/sf = $104.30",
    "Long Description": "Tibetan Wool",
    "Short Description": "60 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "15",
    "Colors": ""
  },
  {
    SKU: "3.1x4.10_30054_28184",
    "Name": "",
    "Price": "$11/sf = $163.90",
    "Long Description": "Tibetan Wool",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "10",
    "Colors": ""
  },
  {
    SKU: "3.1x4.10_30139_28224",
    "Name": "Ric Rac",
    "Price": "$10/sf = $149",
    "Long Description": "Tibetan Wool",
    "Short Description": "60 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "15",
    "Colors": ""
  },
  {
    SKU: "3.1x4.11_30506_2018",
    "Name": "",
    "Price": "$9/sf = $136.44",
    "Long Description": "Tibetan Wool",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "12",
    "Colors": ""
  },
  {
    SKU: "3.1x5_30053_28185",
    "Name": "",
    "Price": "$11/sf = $169.62",
    "Long Description": "Tibetan Wool",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "10",
    "Colors": ""
  },
  {
    SKU: "3.1x5_30081_28188",
    "Name": "",
    "Price": "$11/sf = $169.62",
    "Long Description": "Tibetan Wool",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "10",
    "Colors": ""
  },
  {
    SKU: "3.1x5_30507_28416",
    "Name": "",
    "Price": "$11/sf = $169.62",
    "Long Description": "Tibetan Wool",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "10",
    "Colors": ""
  },
  {
    SKU: "3.1x5_S_2317_296",
    "Name": "Kazak 8",
    "Price": "$6/sf = $90",
    "Long Description": "New Zealand Wool",
    "Short Description": "Soumak (Flatweave)",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "12",
    "Colors": ""
  },
  {
    SKU: "3.1x5.1_29980_27944",
    "Name": "",
    "Price": "$11/sf = $172.37",
    "Long Description": "Tibetan Wool",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "10",
    "Colors": ""
  },
  {
    SKU: "3.1x5.1_30056_28195",
    "Name": "",
    "Price": "$9/sf = $141.03",
    "Long Description": "Tibetan Wool",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "12",
    "Colors": ""
  },
  {
    SKU: "3.1x5.1_30499_28418",
    "Name": "",
    "Price": "$11/sf = $172.37",
    "Long Description": "Tibetan Wool",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "10",
    "Colors": ""
  },
  {
    SKU: "3.1x5.1_30505_28417",
    "Name": "",
    "Price": "$11/sf = $172.37",
    "Long Description": "Tibetan Wool",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "10",
    "Colors": ""
  },
  {
    SKU: "3.1x5.1_30532_28442",
    "Name": "",
    "Price": "$9/sf = $141.03",
    "Long Description": "Tibetan Wool",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "12",
    "Colors": ""
  },
  {
    SKU: "3.1x5.1_32438_29431",
    "Name": "",
    "Price": "$11/sf = $172.37",
    "Long Description": "Tibetan Wool",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "10",
    "Colors": ""
  },
  {
    SKU: "3.1x5.1_32938_29644",
    "Name": "",
    "Price": "$11/sf = $172.37",
    "Long Description": "Tibetan Wool",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "10",
    "Colors": ""
  },
  {
    SKU: "3.1x5.1_32431_3335",
    "Name": "Fleurs de Lis",
    "Price": "$12/sf = $188.04",
    "Long Description": "Tibetan Wool",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "12",
    "Colors": ""
  },
  {
    SKU: "3.1x5.2_29981_27946",
    "Name": "",
    "Price": "$11/sf = $175.23",
    "Long Description": "Tibetan Wool",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "10",
    "Colors": ""
  },
  {
    SKU: "3.1x5.2_32694_3597",
    "Name": "",
    "Price": "$13/sf = $207.09",
    "Long Description": "Tibetan Wool w/Silk",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "10",
    "Colors": ""
  },
  {
    SKU: "3.1x5.2_S_1045_324",
    "Name": "Suzani 11",
    "Price": "$7/sf = $105",
    "Long Description": "New Zealand Wool",
    "Short Description": "Soumak (Flatweave)",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "12",
    "Colors": ""
  },
  {
    SKU: "3.1x5.2_S_1350_626",
    "Name": "Suzani 9",
    "Price": "$7/sf = $105",
    "Long Description": "New Zealand Wool",
    "Short Description": "Soumak (Flatweave)",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "12",
    "Colors": ""
  },
  {
    SKU: "3.1x5.3_S_1842_1112",
    "Name": "Suzani 1",
    "Price": "$7/sf = $105",
    "Long Description": "New Zealand Wool",
    "Short Description": "Soumak (Flatweave)",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "12",
    "Colors": ""
  },
  {
    SKU: "3.2x5_S_1626_897",
    "Name": "Kazak 7",
    "Price": "$6/sf = $90",
    "Long Description": "New Zealand Wool",
    "Short Description": "Soumak (Flatweave)",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "12",
    "Colors": ""
  },
  {
    SKU: "3.2x5.1_S_1317_593",
    "Name": "Suzani 2",
    "Price": "$7/sf = $105",
    "Long Description": "New Zealand Wool",
    "Short Description": "Soumak (Flatweave)",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "12",
    "Colors": ""
  },
  {
    SKU: "3.2x5.3_S_1531_802",
    "Name": "Kazak 6",
    "Price": "$6/sf = $90",
    "Long Description": "New Zealand Wool",
    "Short Description": "Soumak (Flatweave)",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "12",
    "Colors": ""
  },
  {
    SKU: "3.3x5_S_2457_426",
    "Name": "",
    "Price": "$5/sf = $81.25",
    "Long Description": "New Zealand Wool",
    "Short Description": "Soumak (Flatweave)",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "12",
    "Colors": ""
  },
  {
    SKU: "3.11x5.11_27822_26058",
    "Name": "Ric Rac",
    "Price": "$10/sf = $231.70",
    "Long Description": "Tibetan Wool",
    "Short Description": "60 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "23",
    "Colors": ""
  },
  {
    SKU: "3.11x5.11_32408_3351",
    "Name": "",
    "Price": "$9/sf = $208.53",
    "Long Description": "Tibetan Wool",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "20",
    "Colors": ""
  },
  {
    SKU: "3.11x5.11_32946_3648",
    "Name": "",
    "Price": "$9/sf = $208.53",
    "Long Description": "Tibetan Wool",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "20",
    "Colors": ""
  },
  {
    SKU: "3.11x6_30863_2092",
    "Name": "",
    "Price": "$7/sf = $164.50",
    "Long Description": "Tibetan Wool",
    "Short Description": "60 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "23",
    "Colors": ""
  },
  {
    SKU: "3.11x6_32686_3598",
    "Name": "",
    "Price": "$13/sf = $305.50",
    "Long Description": "Tibetan Wool w/Silk",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "16",
    "Colors": ""
  },
  {
    SKU: "3.11x6.1_32418_29413",
    "Name": "",
    "Price": "$12/sf = $285.96",
    "Long Description": "Tibetan Wool",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "16",
    "Colors": ""
  },
  {
    SKU: "3.11x6.3_S_622_667",
    "Name": "Suzani 6",
    "Price": "$7/sf = $105",
    "Long Description": "New Zealand Wool",
    "Short Description": "Soumak (Flatweave)",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "20",
    "Colors": ""
  },
  {
    SKU: "3.11x6_30597_28338",
    "Name": "Retro",
    "Price": "$13/sf = $309.79",
    "Long Description": "Tibetan Wool w/Silk",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "20",
    "Colors": ""
  },
  {
    SKU: "3.11x59_30007_27940",
    "Name": "",
    "Price": "$7/sf = $157.64",
    "Long Description": "Tibetan Wool",
    "Short Description": "60 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "23",
    "Colors": ""
  },
  {
    SKU: "3.x5.2_S_ 1353_629",
    "Name": "Suzani 5",
    "Price": "$7/sf = $105",
    "Long Description": "New Zealand Wool",
    "Short Description": "Soumak (Flatweave)",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "12",
    "Colors": ""
  },
  {
    SKU: "3x4.10_29360_27566",
    "Name": "",
    "Price": "$5/sf = $72.50",
    "Long Description": "Tibetan Wool",
    "Short Description": "60 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "12",
    "Colors": ""
  },
  {
    SKU: "3x4.10_29978_27933",
    "Name": "",
    "Price": "$9/sf = $128.25",
    "Long Description": "Tibetan Wool",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "12",
    "Colors": ""
  },
  {
    SKU: "3x4.11_29997_27999",
    "Name": "",
    "Price": "$9/sf = $132.75",
    "Long Description": "Tibetan Wool",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "12",
    "Colors": ""
  },
  {
    SKU: "3x4.11_31731_2657",
    "Name": "",
    "Price": "$7/sf = $103.25",
    "Long Description": "Tibetan Wool",
    "Short Description": "60 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "15",
    "Colors": ""
  },
  {
    SKU: "3x4.11_32429_3188",
    "Name": "",
    "Price": "$9/sf = $132.75",
    "Long Description": "Tibetan Wool",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "12",
    "Colors": ""
  },
  {
    SKU: "3x5_30079_28180CR2",
    "Name": "",
    "Price": "$11/sf = $165",
    "Long Description": "Tibetan Wool",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "10",
    "Colors": ""
  },
  {
    SKU: "3x5_30082_28187",
    "Name": "",
    "Price": "$11/sf = $165",
    "Long Description": "Tibetan Wool",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "10",
    "Colors": ""
  },
  {
    SKU: "3x5_30492_2023",
    "Name": "",
    "Price": "$9/sf = $135",
    "Long Description": "Tibetan Wool",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "12",
    "Colors": ""
  },
  {
    SKU: "3x5_30531_2021",
    "Name": "",
    "Price": "$9/sf = $135",
    "Long Description": "Tibetan Wool",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "12",
    "Colors": ""
  },
  {
    SKU: "3x5_30534_28441",
    "Name": "",
    "Price": "$11/sf = $165",
    "Long Description": "Tibetan Wool",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "10",
    "Colors": ""
  },
  {
    SKU: "3x5_31325_2613",
    "Name": "",
    "Price": "$9/sf = $135",
    "Long Description": "Tibetan Wool",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "12",
    "Colors": ""
  },
  {
    SKU: "3x5_31537_2659",
    "Name": "",
    "Price": "$9/sf = $135",
    "Long Description": "Tibetan Wool",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "12",
    "Colors": ""
  },
  {
    SKU: "3x5_31729_2526",
    "Name": "",
    "Price": "$9/sf = $135",
    "Long Description": "Tibetan Wool",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "12",
    "Colors": ""
  },
  {
    SKU: "3x5_31730_2658",
    "Name": "",
    "Price": "$7/sf = $105",
    "Long Description": "Tibetan Wool",
    "Short Description": "60 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "15",
    "Colors": ""
  },
  {
    SKU: "3x5_32440_29403",
    "Name": "",
    "Price": "$12/sf = $180",
    "Long Description": "Tibetan Wool",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "10",
    "Colors": ""
  },
  {
    SKU: "3x5_32691_3408",
    "Name": "",
    "Price": "$7/sf = $105",
    "Long Description": "Tibetan Wool",
    "Short Description": "60 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "15",
    "Colors": ""
  },
  {
    SKU: "3x5_32692_3409",
    "Name": "",
    "Price": "$9/sf = $135",
    "Long Description": "Tibetan Wool",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "12",
    "Colors": ""
  },
  {
    SKU: "3x5_32693_3410",
    "Name": "",
    "Price": "$9/sf = $135",
    "Long Description": "Tibetan Wool",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "12",
    "Colors": ""
  },
  {
    SKU: "3x5_32911_3647",
    "Name": "",
    "Price": "$12/sf = $180",
    "Long Description": "Tibetan Wool w/Silk",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "10",
    "Colors": ""
  },
  {
    SKU: "3x5_39348_1686",
    "Name": "",
    "Price": "$9/sf = $135",
    "Long Description": "Tibetan Wool",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "12",
    "Colors": ""
  },
  {
    SKU: "3x5_H_Olive",
    "Name": "",
    "Price": "$19",
    "Long Description": "Hemp",
    "Short Description": "Hemp Rug",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "12",
    "Colors": ""
  },
  {
    SKU: "3x5_H_Walnut",
    "Name": "",
    "Price": "$19",
    "Long Description": "Hemp",
    "Short Description": "Hemp Rug",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "12",
    "Colors": ""
  },
  {
    SKU: "3x5_S_2022_1291",
    "Name": "Kazak 9",
    "Price": "$6/sf = $90",
    "Long Description": "New Zealand Wool",
    "Short Description": "Soumak (Flatweave)",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "12",
    "Colors": ""
  },
  {
    SKU: "3x5.1_29382_27663",
    "Name": "",
    "Price": "$11/sf = $167.75",
    "Long Description": "Tibetan Wool",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "10",
    "Colors": ""
  },
  {
    SKU: "3x5.1_30504_2024",
    "Name": "",
    "Price": "$9/sf = $137.25",
    "Long Description": "Tibetan Wool",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "12",
    "Colors": ""
  },
  {
    SKU: "3x5.1_30886_28571",
    "Name": "",
    "Price": "$11/sf = $167.75",
    "Long Description": "Tibetan Wool",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "10",
    "Colors": ""
  },
  {
    SKU: "3x5.1_31515_2528",
    "Name": "",
    "Price": "$7/sf = $106.75",
    "Long Description": "Tibetan Wool",
    "Short Description": "60 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "15",
    "Colors": ""
  },
  {
    SKU: "3x5.1_31516_2527",
    "Name": "",
    "Price": "$7/sf = $106.75",
    "Long Description": "Tibetan Wool",
    "Short Description": "60 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "15",
    "Colors": ""
  },
  {
    SKU: "3x5.1_S_3173_142",
    "Name": "Suzani 8",
    "Price": "$7/sf = $105",
    "Long Description": "New Zeland Wool",
    "Short Description": "Soumak (Flatweave)",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "12",
    "Colors": ""
  },
  {
    SKU: "3x5.2_S_1320_596",
    "Name": "Suzani 6",
    "Price": "$7/sf = $105",
    "Long Description": "New Zealand Wool",
    "Short Description": "Soumak (Flatweave)",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "12",
    "Colors": ""
  },
  {
    SKU: "3x5.2_S_1839_1110",
    "Name": "Suzani 10",
    "Price": "$7/sf = $105",
    "Long Description": "New Zealand Wool",
    "Short Description": "Soumak (Flatweave)",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "12",
    "Colors": ""
  },
  {
    SKU: "3x5.3_30055_28182",
    "Name": "",
    "Price": "$11/sf = $173.25",
    "Long Description": "Tibetan Wool",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "10",
    "Colors": ""
  },
  {
    SKU: "4.1x 6_32923_29643",
    "Name": "",
    "Price": "$13/sf = $318.50",
    "Long Description": "Tibetan Wool w/Silk",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "16",
    "Colors": ""
  },
  {
    SKU: "4.1x5.11_S_2440_409",
    "Name": "Mamluk",
    "Price": "$7/sf = $168",
    "Long Description": "New Zealand Wool",
    "Short Description": "Soumak (Flatweave)",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "20",
    "Colors": ""
  },
  {
    SKU: "4.1x6_32926_29603",
    "Name": "",
    "Price": "$13/sf = $318.50",
    "Long Description": "Tibetan Wool w/Silk",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "16",
    "Colors": ""
  },
  {
    SKU: "4.1x6_32984_29667",
    "Name": "",
    "Price": "$13/sf = $318.50",
    "Long Description": "Tiebtan Wool",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "16",
    "Colors": ""
  },
  {
    SKU: "4.1x6_S_1178_457",
    "Name": "Suzani 9",
    "Price": "$7/sf = $168",
    "Long Description": "New Zealand Wool",
    "Short Description": "Soumak (Flatweave)",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "20",
    "Colors": ""
  },
  {
    SKU: "4.1x6_S_1864_1136",
    "Name": "Kazak 10",
    "Price": "$6/sf = $144",
    "Long Description": "New Zealand Wool",
    "Short Description": "Soumak (Flatweave)",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "20",
    "Colors": ""
  },
  {
    SKU: "4.1x6_S_2456_425",
    "Name": "",
    "Price": "$6/sf = $144",
    "Long Description": "New Zealand Wool",
    "Short Description": "Soumak (Flatweave)",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "20",
    "Colors": ""
  },
  {
    SKU: "4.1x6.1_30011_28000",
    "Name": "",
    "Price": "$7/sf = $168",
    "Long Description": "Tibetan Wool",
    "Short Description": "60 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "23",
    "Colors": ""
  },
  {
    SKU: "4.1x6.1_31201_2322",
    "Name": "",
    "Price": "$12/sf = $298.08",
    "Long Description": "Tibetan Wool w/Linen",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "20",
    "Colors": ""
  },
  {
    SKU: "4.1x6.1_32414_29400",
    "Name": "",
    "Price": "$11/sf = $273.24",
    "Long Description": "Tibetan Wool",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "16",
    "Colors": ""
  },
  {
    SKU: "4.1x6.1_S_1054_333",
    "Name": "Suzani 2",
    "Price": "$7/sf = $168",
    "Long Description": "New Zealand Wool",
    "Short Description": "Soumak (Flatweave)",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "20",
    "Colors": ""
  },
  {
    SKU: "4.1x6.1_S_2441_410",
    "Name": "",
    "Price": "$7/sf = $168",
    "Long Description": "New Zealand Wool",
    "Short Description": "Soumak (Flatweave)",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "20",
    "Colors": ""
  },
  {
    SKU: "4.1x6.2_S_386_442",
    "Name": "Kazak 6",
    "Price": "$6/sf = $144",
    "Long Description": "New Zealand Wool",
    "Short Description": "Soumak (Flatweave)",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "20",
    "Colors": ""
  },
  {
    SKU: "4.1x6.2_S_2446_415",
    "Name": "Pazyryk",
    "Price": "$7/sf = $168",
    "Long Description": "New Zealand Wool",
    "Short Description": "Soumak (Flatweave)",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "20",
    "Colors": ""
  },
  {
    SKU: "4.1x6.2_S_2452_421",
    "Name": "Pazyryk",
    "Price": "$7/sf = $168",
    "Long Description": "New Zealand Wool",
    "Short Description": "Soumak (Flatweave)",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "20",
    "Colors": ""
  },
  {
    SKU: "4.1x6.2_S_2453_422",
    "Name": "Pazyryk",
    "Price": "$7/sf = $168",
    "Long Description": "New Zealand Wool",
    "Short Description": "Soumak (Flatweave)",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "20",
    "Colors": ""
  },
  {
    SKU: "4.1x6.3_S_2450_419",
    "Name": "Pazyryk",
    "Price": "$7/sf = $168",
    "Long Description": "New Zealand Wool",
    "Short Description": "Soumak (Flatweave)",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "20",
    "Colors": ""
  },
  {
    SKU: "4.1x6.3_S_2451_420",
    "Name": "Pazyryk",
    "Price": "$7/sf = $168",
    "Long Description": "New Zealand Wool",
    "Short Description": "Soumak (Flatweave)",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "20",
    "Colors": ""
  },
  {
    SKU: "4.2x6_S_2743_287",
    "Name": "Suzani 9",
    "Price": "$7/sf = $168",
    "Long Description": "New Zealand Wool",
    "Short Description": "Soumak (Flatweave)",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "20",
    "Colors": ""
  },
  {
    SKU: "4.2x6.1_S_2455_424",
    "Name": "Mamluk",
    "Price": "$7/sf = $168",
    "Long Description": "New Zealand Wool",
    "Short Description": "Soumak (Flatweave)",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "20",
    "Colors": ""
  },
  {
    SKU: "4.2x6.1_S_2559_102",
    "Name": "",
    "Price": "$7/sf = $168",
    "Long Description": "New Zealand Wool",
    "Short Description": "Soumak (Flatweave)",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "20",
    "Colors": ""
  },
  {
    SKU: "4.2x6.2_S_2447_416",
    "Name": "Pazyryk",
    "Price": "$7/sf = $168",
    "Long Description": "New Zealand Wool",
    "Short Description": "Soumak (Flatweave)",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "20",
    "Colors": ""
  },
  {
    SKU: "4.2x6.2_S_2454_423",
    "Name": "Pazyryk",
    "Price": "$7/sf = $168",
    "Long Description": "New Zealand Wool",
    "Short Description": "Soumak (Flatweave)",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "20",
    "Colors": ""
  },
  {
    SKU: "4.2x6.3_S_1972_1241",
    "Name": "Suzani 5",
    "Price": "$7/sf = $168",
    "Long Description": "New Zealand Wool",
    "Short Description": "Soumak (Flatweave)",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "20",
    "Colors": ""
  },
  {
    SKU: "4x5.8_30868_2087",
    "Name": "",
    "Price": "$7/sf = $168",
    "Long Description": "Tibetan Wool",
    "Short Description": "60 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "23",
    "Colors": ""
  },
  {
    SKU: "4x5.10_30873_2086",
    "Name": "",
    "Price": "$7/sf = $168",
    "Long Description": "Tibetan Wool",
    "Short Description": "60 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "23",
    "Colors": ""
  },
  {
    SKU: "4x5.10_32176_29282",
    "Name": "",
    "Price": "$11/sf = $256.63",
    "Long Description": "Tibetan Wool",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "16",
    "Colors": ""
  },
  {
    SKU: "4x5.11_28811_26845",
    "Name": "",
    "Price": "$7/sf = $165.69",
    "Long Description": "Tibetan Wool",
    "Short Description": "60 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "23",
    "Colors": ""
  },
  {
    SKU: "4x5.11_30009_27937",
    "Name": "",
    "Price": "$7/sf = $165.69",
    "Long Description": "Tibetan Wool",
    "Short Description": "60 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "23",
    "Colors": ""
  },
  {
    SKU: "4x5.11_30062_28231",
    "Name": "",
    "Price": "$7/sf = $165.69",
    "Long Description": "Tibetan Wool",
    "Short Description": "60 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "23",
    "Colors": ""
  },
  {
    SKU: "4x5.11_30587_28443",
    "Name": "",
    "Price": "$9/sf = $213.03",
    "Long Description": "Tibetan Wool",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "20",
    "Colors": ""
  },
  {
    SKU: "4x5.11_30866_2084",
    "Name": "",
    "Price": "$7/sf = $165.69",
    "Long Description": "Tibetan Wool",
    "Short Description": "60",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "23",
    "Colors": ""
  },
  {
    SKU: "4x5.11_30878_2076",
    "Name": "",
    "Price": "$11/sf = $260.37",
    "Long Description": "Tibetan Wool",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "16",
    "Colors": ""
  },
  {
    SKU: "4x5.11_32173_29280",
    "Name": "",
    "Price": "$12/sf = $284.04",
    "Long Description": "Tibetan Wool",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "16",
    "Colors": ""
  },
  {
    SKU: "4x5.11_32175_29254",
    "Name": "",
    "Price": "$12/sf = $284.04",
    "Long Description": "Tibetan Wool",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "16",
    "Colors": ""
  },
  {
    SKU: "4x5.11_32496_3366",
    "Name": "",
    "Price": "$9/sf = $213.03",
    "Long Description": "Tibetan Wool",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "20",
    "Colors": ""
  },
  {
    SKU: "4x5.11_32927_3604",
    "Name": "",
    "Price": "$9/sf = $213.03",
    "Long Description": "Tibetan Wool",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "20",
    "Colors": ""
  },
  {
    SKU: "4x5.11_32947_29683",
    "Name": "",
    "Price": "$11/sf = $260.37",
    "Long Description": "Tibetan Wool",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "16",
    "Colors": ""
  },
  {
    SKU: "4x5.11_32983_29731",
    "Name": "",
    "Price": "$13/sf = $307.71",
    "Long Description": "Tibetan Wool w/Silk",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "16",
    "Colors": ""
  },
  {
    SKU: "4x5.11_S_1862_1132",
    "Name": "Kazak 9",
    "Price": "$6/sf = $144",
    "Long Description": "New Zealand Wool",
    "Short Description": "Soumak (Flatweave)",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "20",
    "Colors": ""
  },
  {
    SKU: "4x6_3007T",
    "Name": "M2",
    "Price": "$4/sf = $96",
    "Long Description": "Tibetan Wool",
    "Short Description": "60 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "23",
    "Colors": ""
  },
  {
    SKU: "4x6_28353_26583",
    "Name": "",
    "Price": "$7/sf = $168",
    "Long Description": "Tibetan Wool",
    "Short Description": "60 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "23",
    "Colors": ""
  },
  {
    SKU: "4x6_28354_26584",
    "Name": "",
    "Price": "$7/sf = $168",
    "Long Description": "Tibetan Wool",
    "Short Description": "60 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "23",
    "Colors": ""
  },
  {
    SKU: "4x6_30063_28233",
    "Name": "",
    "Price": "$7/sf = $168",
    "Long Description": "Tibetan Wool",
    "Short Description": "60 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "23",
    "Colors": ""
  },
  {
    SKU: "4x6_30861_2093",
    "Name": "",
    "Price": "$7/sf = $168",
    "Long Description": "Tibetan Wool",
    "Short Description": "60 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "23",
    "Colors": ""
  },
  {
    SKU: "4x6_30862_2085",
    "Name": "",
    "Price": "$7/sf = $168",
    "Long Description": "Tibetan Wool",
    "Short Description": "60 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "23",
    "Colors": ""
  },
  {
    SKU: "4x6_30867_2095",
    "Name": "",
    "Price": "$7/sf = $168",
    "Long Description": "Tibetan Wool",
    "Short Description": "60 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "23",
    "Colors": ""
  },
  {
    SKU: "4x6_30869_2090",
    "Name": "",
    "Price": "$9/sf = $216",
    "Long Description": "Tibetan Wool",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "20",
    "Colors": ""
  },
  {
    SKU: "4x6_30871_2098",
    "Name": "",
    "Price": "$7/sf = $168",
    "Long Description": "Tibetan Wool",
    "Short Description": "60 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "23",
    "Colors": ""
  },
  {
    SKU: "4x6_30874_2094",
    "Name": "",
    "Price": "$7/sf = $168",
    "Long Description": "Tibetan Wool",
    "Short Description": "60 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "23",
    "Colors": ""
  },
  {
    SKU: "4x6_30875_28532",
    "Name": "",
    "Price": "$7/sf = $168",
    "Long Description": "Tibetan Wool",
    "Short Description": "60 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "23",
    "Colors": ""
  },
  {
    SKU: "4x6_30876_28533",
    "Name": "",
    "Price": "$7/sf = $168",
    "Long Description": "Tibetan Wool",
    "Short Description": "60 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "23",
    "Colors": ""
  },
  {
    SKU: "4x6_30877_28560",
    "Name": "",
    "Price": "$11/sf = $264",
    "Long Description": "Tibetan Wool",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "16",
    "Colors": ""
  },
  {
    SKU: "4x6_30880_2091",
    "Name": "",
    "Price": "$9/sf = $216",
    "Long Description": "Tibetan Wool",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "20",
    "Colors": ""
  },
  {
    SKU: "4x6_30881_2088",
    "Name": "",
    "Price": "$9/sf = $216",
    "Long Description": "Tibetan Wool",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "20",
    "Colors": ""
  },
  {
    SKU: "4x6_31499_2604",
    "Name": "",
    "Price": "$7/sf = $168",
    "Long Description": "Tibetan Wool",
    "Short Description": "60 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "23",
    "Colors": ""
  },
  {
    SKU: "4x6_31688_39014",
    "Name": "Diamondback",
    "Price": "$14/sf = $336",
    "Long Description": "Tibetan Wool w/Silk",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "16",
    "Colors": ""
  },
  {
    SKU: "4x6_31742_2790",
    "Name": "Tiger's Eye",
    "Price": "$12/sf = $288",
    "Long Description": "Tibetan Wool",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "20",
    "Colors": ""
  },
  {
    SKU: "4x6_31760_29155",
    "Name": "",
    "Price": "$12/sf = $288",
    "Long Description": "Tibetan Wool",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "16",
    "Colors": ""
  },
  {
    SKU: "4x6_32007_29340",
    "Name": "",
    "Price": "$12/sf = $288",
    "Long Description": "Tibetan Wool",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "16",
    "Colors": ""
  },
  {
    SKU: "4x6_32170_29281",
    "Name": "",
    "Price": "$11/sf = $264",
    "Long Description": "Tibetan Wool",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "16",
    "Colors": ""
  },
  {
    SKU: "4x6_32172_29284",
    "Name": "",
    "Price": "$12/sf = $288",
    "Long Description": "Tibetan Wool",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "16",
    "Colors": ""
  },
  {
    SKU: "4x6_32174_29259",
    "Name": "",
    "Price": "$12/sf = $288",
    "Long Description": "Tibetan Wool",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "16",
    "Colors": ""
  },
  {
    SKU: "4x6_32177_29283",
    "Name": "",
    "Price": "$11/sf = $264",
    "Long Description": "Tibetan Wool",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "16",
    "Colors": ""
  },
  {
    SKU: "4x6_32405_3352",
    "Name": "",
    "Price": "$7/sf = $168",
    "Long Description": "Tibetan Wool",
    "Short Description": "60 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "23",
    "Colors": ""
  },
  {
    SKU: "4x6_32407_3350",
    "Name": "",
    "Price": "$9/sf = $216",
    "Long Description": "Tibetan Wool",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "20",
    "Colors": ""
  },
  {
    SKU: "4x6_32419_29399",
    "Name": "",
    "Price": "$11/sf = $264",
    "Long Description": "Tibetan Wool",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "16",
    "Colors": ""
  },
  {
    SKU: "4x6_32493_29437",
    "Name": "",
    "Price": "$12/sf = $288",
    "Long Description": "Tibetan Wool",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "16",
    "Colors": ""
  },
  {
    SKU: "4x6_32494_3367",
    "Name": "",
    "Price": "$11/sf = $264",
    "Long Description": "Tibetan Wool w/Silk",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "20",
    "Colors": ""
  },
  {
    SKU: "4x6_32653_3368",
    "Name": "",
    "Price": "$11/sf = $264",
    "Long Description": "Tibetan Wool",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "20",
    "Colors": ""
  },
  {
    SKU: "4x6_32920_29564",
    "Name": "",
    "Price": "$13/sf = $312",
    "Long Description": "Tibetan Wool w/Silk",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "16",
    "Colors": ""
  },
  {
    SKU: "4x6_32921_29642",
    "Name": "",
    "Price": "$13/sf = $312",
    "Long Description": "Tibetan Wool w/Silk",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "16",
    "Colors": ""
  },
  {
    SKU: "4x6_32922_29602",
    "Name": "",
    "Price": "$12/sf = $288",
    "Long Description": "Tibetan Wool",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "16",
    "Colors": ""
  },
  {
    SKU: "4x6_32925_29648",
    "Name": "",
    "Price": "$12/sf = $288",
    "Long Description": "Tibetan Wool",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "16",
    "Colors": ""
  },
  {
    SKU: "4x6_H_Walnut",
    "Name": "",
    "Price": "$31",
    "Long Description": "Hemp",
    "Short Description": "Hemp Rug",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "20",
    "Colors": ""
  },
  {
    SKU: "4x6.1_30059_28235",
    "Name": "",
    "Price": "$7/sf = $170.31",
    "Long Description": "Tibetan Wool",
    "Short Description": "60 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "23",
    "Colors": ""
  },
  {
    SKU: "4x6.1_30060_28232",
    "Name": "",
    "Price": "$7/sf = $170.31",
    "Long Description": "Tibetan Wool",
    "Short Description": "60 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "23",
    "Colors": ""
  },
  {
    SKU: "4x6.1_30515_28399",
    "Name": "",
    "Price": "$11/sf = $267.63",
    "Long Description": "Tibetan Wool",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "16",
    "Colors": ""
  },
  {
    SKU: "4x6.1_30859_2100",
    "Name": "",
    "Price": "$7/sf = $170.31",
    "Long Description": "Tibetan Wool",
    "Short Description": "60 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "23",
    "Colors": ""
  },
  {
    SKU: "4x6.1_31759_29178",
    "Name": "",
    "Price": "$11/sf = $267.63",
    "Long Description": "Tibetan Wool",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "16",
    "Colors": ""
  },
  {
    SKU: "4x6.1_32265_29401",
    "Name": "",
    "Price": "$13/sf = $316.29",
    "Long Description": "Tibetan Wool",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "16",
    "Colors": ""
  },
  {
    SKU: "4x6.1_32266_29373",
    "Name": "",
    "Price": "$12/sf = $291.96",
    "Long Description": "Tibetan Wool",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "16",
    "Colors": ""
  },
  {
    SKU: "4x6.1_32652_3367",
    "Name": "",
    "Price": "$9/sf = $223.56",
    "Long Description": "Tibetan Wool",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "20",
    "Colors": ""
  },
  {
    SKU: "4x6.1_S_1415_691",
    "Name": "Kazak 1",
    "Price": "$6/sf = $144",
    "Long Description": "New Zealand Wool",
    "Short Description": "Soumak (Flatweave)",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "20",
    "Colors": ""
  },
  {
    SKU: "4x6.2_32171_29285",
    "Name": "",
    "Price": "$12/sf = $296.04",
    "Long Description": "Tibetan Wool",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "16",
    "Colors": ""
  },
  {
    SKU: "4x6.3_30858_2083",
    "Name": "",
    "Price": "$7/sf = $175",
    "Long Description": "Tibetan Wool",
    "Short Description": "60 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "23",
    "Colors": ""
  },
  {
    SKU: "4x6.3_31500_2605",
    "Name": "",
    "Price": "$7/sf = $175",
    "Long Description": "Tibetan Wool",
    "Short Description": "60 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "23",
    "Colors": ""
  },
  {
    SKU: "4x6.3_32006_29339",
    "Name": "",
    "Price": "$12/sf = $300",
    "Long Description": "Tibetan Wool",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "16",
    "Colors": ""
  },
  {
    SKU: "5.1x7.5_31681_2911",
    "Name": "Diamondback",
    "Price": "$14/sf = $527.80",
    "Long Description": "Tibetan Wool w/Silk",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "26",
    "Colors": ""
  },
  {
    SKU: "5.10x8.10_20703_19658",
    "Name": "",
    "Price": "$5/sf = $257.65",
    "Long Description": "Tibetan Wool",
    "Short Description": "60 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "50",
    "Colors": ""
  },
  {
    SKU: "5.10x9_20691_19749",
    "Name": "",
    "Price": "$5/sf = $262.50",
    "Long Description": "Tibetan Wool",
    "Short Description": "60 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "50",
    "Colors": ""
  },
  {
    SKU: "5.10x9_20834_19907",
    "Name": "",
    "Price": "$5/sf = $262.50",
    "Long Description": "Tibetan Wool",
    "Short Description": "60 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "50",
    "Colors": ""
  },
  {
    SKU: "5.10x9_26608_24921",
    "Name": "",
    "Price": "$7/sf = $367.50",
    "Long Description": "Tibetan Wool",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "37",
    "Colors": ""
  },
  {
    SKU: "5.10x9_28213_26300",
    "Name": "",
    "Price": "$5/sf = $262.50",
    "Long Description": "Tibetan Wool",
    "Short Description": "60 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "50",
    "Colors": ""
  },
  {
    SKU: "5.10x9.1_20656_19810",
    "Name": "",
    "Price": "$9/sf = $476.91",
    "Long Description": "Tibetan Wool",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "34",
    "Colors": ""
  },
  {
    SKU: "5.11x8.10_20606_19655",
    "Name": "",
    "Price": "$5/sf = $261.30",
    "Long Description": "Tibetan Wool",
    "Short Description": "60 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "50",
    "Colors": ""
  },
  {
    SKU: "5.11x8.10_20624_19681",
    "Name": "",
    "Price": "$5/sf = $261.30",
    "Long Description": "Tibetan Wool",
    "Short Description": "60 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "50",
    "Colors": ""
  },
  {
    SKU: "5.11x8.10_20658_19812",
    "Name": "",
    "Price": "$9/sf = $470.34",
    "Long Description": "Tibetan Wool",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "34",
    "Colors": ""
  },
  {
    SKU: "5.11x8.10_32930_3745",
    "Name": "",
    "Price": "$9/sf = $470.34",
    "Long Description": "Tibetan Wool",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "37",
    "Colors": ""
  },
  {
    SKU: "5.11x8.11_20651_19828",
    "Name": "",
    "Price": "$9/sf = $474.84",
    "Long Description": "Tibetan Wool",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "34",
    "Colors": ""
  },
  {
    SKU: "5.11x8.11_20652_19826",
    "Name": "",
    "Price": "$9/sf = $474.84",
    "Long Description": "Tibetan Wool",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "34",
    "Colors": ""
  },
  {
    SKU: "5.11x8.11_20659_19779",
    "Name": "",
    "Price": "$9/sf = $474.84",
    "Long Description": "Tibetan Wool",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "34",
    "Colors": ""
  },
  {
    SKU: "5.11x8.11_20692_19714",
    "Name": "",
    "Price": "$5/sf = $263.80",
    "Long Description": "Tibetan Wool",
    "Short Description": "60 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "50",
    "Colors": ""
  },
  {
    SKU: "5.11x8.11_20698_19818",
    "Name": "",
    "Price": "$5/sf = $263.80",
    "Long Description": "Tibetan Wool",
    "Short Description": "60 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "50",
    "Colors": ""
  },
  {
    SKU: "5.11x8.11_20848_20061",
    "Name": "",
    "Price": "$5/sf = $263.80",
    "Long Description": "Tibetan Wool",
    "Short Description": "60 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "50",
    "Colors": ""
  },
  {
    SKU: "5.11x8.11_23073_22256",
    "Name": "",
    "Price": "$7/sf = $369.32",
    "Long Description": "Tibetan Wool",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "37",
    "Colors": ""
  },
  {
    SKU: "5.11x8.11_26314_24642",
    "Name": "",
    "Price": "$7/sf = $369.32",
    "Long Description": "Tibetan Wool",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "37",
    "Colors": ""
  },
  {
    SKU: "5.11x8.11_26610_24963",
    "Name": "",
    "Price": "$7/sf = $369.32",
    "Long Description": "Tibetan Wool",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "37",
    "Colors": ""
  },
  {
    SKU: "5.11x8.11_26611_24922",
    "Name": "",
    "Price": "$7/sf = $369.32",
    "Long Description": "Tibetan Wool",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "37",
    "Colors": ""
  },
  {
    SKU: "5.11x8.11_26614_24962",
    "Name": "",
    "Price": "$8/sf = $422.08",
    "Long Description": "Tibetan Wool",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "34",
    "Colors": ""
  },
  {
    SKU: "5.11x8.11_26984_25206",
    "Name": "",
    "Price": "$5/sf = $263.80",
    "Long Description": "Tibetan Wool",
    "Short Description": "60 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "50",
    "Colors": ""
  },
  {
    SKU: "5.11x8.11_27200_25420",
    "Name": "",
    "Price": "$7/sf = $369.32",
    "Long Description": "Tibetan Wool",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "37",
    "Colors": ""
  },
  {
    SKU: "5.11x8.11_29202_26648",
    "Name": "",
    "Price": "$9/sf = $474.84",
    "Long Description": "Tibetan Wool",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "34",
    "Colors": ""
  },
  {
    SKU: "5.11x8.11_30856_28562",
    "Name": "",
    "Price": "$11/sf = $580.36",
    "Long Description": "Tibetan Wool",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "34",
    "Colors": ""
  },
  {
    SKU: "5.11x9_20704_745",
    "Name": "",
    "Price": "$5/sf = $266.25",
    "Long Description": "Tibetan Wool",
    "Short Description": "60 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "50",
    "Colors": ""
  },
  {
    SKU: "5.11x9_20820_19972",
    "Name": "",
    "Price": "$5/sf = $266.25",
    "Long Description": "Tibetan Wool",
    "Short Description": "60 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "50",
    "Colors": ""
  },
  {
    SKU: "5.11x9_21452_20638",
    "Name": "",
    "Price": "$5/sf = $266.25",
    "Long Description": "Tibetan Wool",
    "Short Description": "60 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "50",
    "Colors": ""
  },
  {
    SKU: "5.11x9_26315_24533",
    "Name": "",
    "Price": "$5/sf = $266.25",
    "Long Description": "Tibetan Wool",
    "Short Description": "60 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "50",
    "Colors": ""
  },
  {
    SKU: "5.11x9_26602_24868",
    "Name": "",
    "Price": "$11/sf = $585.75",
    "Long Description": "Tibetan Wool",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "34",
    "Colors": ""
  },
  {
    SKU: "5.11x9_26968_25178",
    "Name": "",
    "Price": "$11/sf = $585.75",
    "Long Description": "Tibetan Wool",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "34",
    "Colors": ""
  },
  {
    SKU: "5.11x9_28799_26918",
    "Name": "",
    "Price": "$11/sf = $585.75",
    "Long Description": "Tibetan Wool",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "34",
    "Colors": ""
  },
  {
    SKU: "5.11x9_33120_29736",
    "Name": "",
    "Price": "$13/sf = $692.25",
    "Long Description": "Tibetan Wool",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "34",
    "Colors": ""
  },
  {
    SKU: "5.11x9_S_631_676",
    "Name": "Kazak 8",
    "Price": "$6/sf = $324",
    "Long Description": "New Zealand Wool",
    "Short Description": "Soumak (Flatweave)",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "37",
    "Colors": ""
  },
  {
    SKU: "5.11x9.1_26990_25231",
    "Name": "",
    "Price": "$7/sf = $376.18",
    "Long Description": "Tibetan Wool",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "37",
    "Colors": ""
  },
  {
    SKU: "5.11x9.2_20814_19950",
    "Name": "",
    "Price": "$5/sf = $271.20",
    "Long Description": "Tibetan Wool",
    "Short Description": "60 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "50",
    "Colors": ""
  },
  {
    SKU: "5.11x9.2_27224_25241",
    "Name": "",
    "Price": "$7/sf = $379.68",
    "Long Description": "Tibetan Wool",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "37",
    "Colors": ""
  },
  {
    SKU: "5.11x9.5_36993_25221",
    "Name": "",
    "Price": "$11/sf = $612.92",
    "Long Description": "Tibetan Wool",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "34",
    "Colors": ""
  },
  {
    SKU: "5x6.11_31682_2710",
    "Name": "Cubes",
    "Price": "$13/sf = $449.54",
    "Long Description": "Tibetan Wool w/Linen",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "26",
    "Colors": ""
  },
  {
    SKU: "5x7_30113_1792",
    "Name": "Fleurs-de-Lis",
    "Price": "$12/sf = $420",
    "Long Description": "Tibetan Wool",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "26",
    "Colors": ""
  },
  {
    SKU: "5x7_30659_2055",
    "Name": "",
    "Price": "$9/sf = $315",
    "Long Description": "Tibetan Wool",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "26",
    "Colors": ""
  },
  {
    SKU: "5x7.1_31885_2854",
    "Name": "Tiger's Eye",
    "Price": "$12/sf = $425.04",
    "Long Description": "Tibetan Wool",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "26",
    "Colors": ""
  },
  {
    SKU: "6.1x6_18523_608",
    "Name": "",
    "Price": "$11/sf = $396",
    "Long Description": "Tibetan Wool",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "34",
    "Colors": ""
  },
  {
    SKU: "6.1x8.10_20041_19472",
    "Name": "",
    "Price": "$5/sf = $268.70",
    "Long Description": "Tibetan Wool",
    "Short Description": "60 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "50",
    "Colors": ""
  },
  {
    SKU: "6.1x8.10_20630_19657",
    "Name": "",
    "Price": "$5/sf = $268.70",
    "Long Description": "Tibetan Wool",
    "Short Description": "60 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "50",
    "Colors": ""
  },
  {
    SKU: "6.1x8.10_32602_29494",
    "Name": "",
    "Price": "$13/sf = $698.62",
    "Long Description": "Tibetan Wool",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "34",
    "Colors": ""
  },
  {
    SKU: "6.1x8.11_20850_20050",
    "Name": "",
    "Price": "$7/sf = $379.68",
    "Long Description": "Tibetan Wool",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "37",
    "Colors": ""
  },
  {
    SKU: "6.1x8.11_32021_29374",
    "Name": "",
    "Price": "$13/sf = $705.12",
    "Long Description": "Tibetan Wool",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "34",
    "Colors": ""
  },
  {
    SKU: "6.1x9_20657_19784",
    "Name": "",
    "Price": "$9/sf = $492.75",
    "Long Description": "Tibetan Wool",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "34",
    "Colors": ""
  },
  {
    SKU: "6.1x9_29191_27299",
    "Name": "",
    "Price": "$9/sf = $492.75",
    "Long Description": "Tibetan Wool",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "37",
    "Colors": ""
  },
  {
    SKU: "6.1x9_30778_28561",
    "Name": "",
    "Price": "$11/sf = $602.25",
    "Long Description": "Tibetan Wool",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "34",
    "Colors": ""
  },
  {
    SKU: "6.1x9_30788_2154",
    "Name": "",
    "Price": "$7/sf = $383.25",
    "Long Description": "Tibetan Wool",
    "Short Description": "60 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "50",
    "Colors": ""
  },
  {
    SKU: "6.1x9_30789_2150",
    "Name": "",
    "Price": "$7/sf = $383.25",
    "Long Description": "Tibetan Wool",
    "Short Description": "60 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "50",
    "Colors": ""
  },
  {
    SKU: "6.1x9_31138_2278",
    "Name": "",
    "Price": "$13sf = $711.75",
    "Long Description": "Tibetan Wool w/Silk Blend",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "37",
    "Colors": ""
  },
  {
    SKU: "6.1x9_31288_2135",
    "Name": "",
    "Price": "$7/sf = $383.25",
    "Long Description": "Tibetan Wool",
    "Short Description": "60 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "50",
    "Colors": ""
  },
  {
    SKU: "6.1x9_31318_29055-2",
    "Name": "",
    "Price": "$11/sf = $602.25",
    "Long Description": "Tibetan Wool",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "34",
    "Colors": ""
  },
  {
    SKU: "6.1x9_32959_3741",
    "Name": "",
    "Price": "$8/sf = $438",
    "Long Description": "Tibetan Wool",
    "Short Description": "60 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "50",
    "Colors": ""
  },
  {
    SKU: "6.1x9_32962_3823",
    "Name": "",
    "Price": "$14/sf = $711.75",
    "Long Description": "Tibetan Wool w/Linen Blend",
    "Short Description": "100 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "34",
    "Colors": ""
  },
  {
    SKU: "6.1x9_S_2080_49",
    "Name": "",
    "Price": "$7/sf = $378",
    "Long Description": "New Zealand Wool",
    "Short Description": "Soumak (Flatweave)",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "37",
    "Colors": ""
  },
  {
    SKU: "6.1x9_S_2093_62",
    "Name": "",
    "Price": "$7/sf = $378",
    "Long Description": "New Zealand Wool",
    "Short Description": "Soumak (Flatweave)",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "37",
    "Colors": ""
  },
  {
    SKU: "6.1x9.1_20830_816",
    "Name": "",
    "Price": "$5/sf = $276.30",
    "Long Description": "Tibetan Wool",
    "Short Description": "60 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "50",
    "Colors": ""
  },
  {
    SKU: "6.1x9.1_29401_27458",
    "Name": "Lotus",
    "Price": "$13/sf = $718.38",
    "Long Description": "Tibetan Wool w/Silk",
    "Short Description": "80 knot",
    "Width": "",
    "Height": "",
    "Qty": 1,
    "Weight": "37",
    "Colors": ""
  }
];
