import './Montserrat-SemiBold.ttf';
import './Montserrat-SemiBold.woff';
import './Montserrat-Regular.eot';
import './Montserrat-Regular.ttf';
import './Montserrat-Medium.eot';
import './Montserrat-Medium.ttf';
import './Montserrat-Light.eot';
import './Montserrat-Light.ttf';
import './Montserrat-Light.woff';
