# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: archadon-${self:custom.env}
plugins:
  - serverless-webpack
provider:
  name: aws
  runtime: nodejs6.10
  profile: archadon
  environment:
    ASSET_URL: ${opt:assetUrl, self:custom.assetUrl}
    NODE_ENV: ${env:NODE_ENV, self:custom.NODE_ENV}
    ALGOLIA_API_KEY: ${file(${opt:secrets}):ALGOLIA_API_KEY}
    ALGOLIA_SECRET_KEY: ${file(${opt:secrets}):ALGOLIA_SECRET_KEY}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
        - "s3:*"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "ses:SendRawEmail"
      Resource: "arn:aws:ses:us-east-1:478433309488:identity/archadon.com"
custom:
  webpack: ./webpack/prod.js
  assetUrl: "https://assets.dev.archadon.com"
  env: ${opt:env, self:provider.stage}
  NODE_ENV: "development"
  UserDataTable: ${self:resources.Resources.UserDataTable.Properties.TableName}
  UserItemTable: ${self:resources.Resources.UserItemTable.Properties.TableName}
  ProductDataTable: ${self:resources.Resources.ProductDataTable.Properties.TableName}
  ProductItemTable: ${self:resources.Resources.ProductItemTable.Properties.TableName}
  OrderDataTable: ${self:resources.Resources.OrderDataTable.Properties.TableName}
  OrderItemTable: ${self:resources.Resources.OrderItemTable.Properties.TableName}

package:
  individually: true
  # include:
  #   - node_modules/**
  #   - functions/utils/**
  #   - templates/**

functions:
  getUserData:
    handler: functions/handlers.getUserData
    events:
      - http:
          path: user/v1/read/{id}
          method: get
          cors:
            origins:
              - '*'
            headers:
              - authtoken
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
          request:
            parameters:
              paths:
                id: true
    environment:
      USER_PROFILE_TABLE: ${self:custom.UserDataTable}
      USER_TABLE: ${self:custom.UserItemTable}
      ORDER_DATA_TABLE: ${self:custom.OrderDataTable}
      ORDER_ITEM_TABLE: ${self:custom.OrderItemTable}

  updateUserProfile:
    handler: functions/user/update/updateUserProfile.updateUserProfile
    events:
      - http:
          path: user/v1/update/data/{id}
          method: post
          cors:
            origins:
              - '*'
            headers:
              - authtoken
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
          request:
            parameters:
              paths:
                id: true
    environment:
      MONGO_URI:  ${file(${opt:secrets}):MONGO_URI}

  updateUserPassword:
    handler: functions/user/update/updateUserPassword.updateUserPassword
    events:
      - http:
          path: user/v1/update/item/password/{id}
          method: post
          cors:
            origins:
              - '*'
            headers:
              - authtoken
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
          request:
            parameters:
              paths:
                id: true
    environment:
      MONGO_URI:  ${file(${opt:secrets}):MONGO_URI}

  updateUserEmail:
    handler: functions/handlers.updateUserEmail
    events:
      - http:
          path: user/v1/update/item/email/{id}
          method: post
          cors:
            origins:
              - '*'
            headers:
              - authtoken
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
          request:
            parameters:
              paths:
                id: true
    environment:
      USER_TABLE: ${self:custom.UserItemTable}

  createUser:
    handler: functions/user/create/index.createUser
    events:
      - http:
          path: user/v1/create
          method: post
          cors:
            origins:
              - '*'
            headers:
              - authtoken
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
    environment:
      MONGO_URI:  ${file(${opt:secrets}):MONGO_URI}
  loginUser:
    handler: functions/user/login/index.login
    events:
      - http:
          path: user/v1/login
          cors:
            origins:
              - '*'
            headers:
              - authtoken
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
          method: post
    environment:
      MONGO_URI:  ${file(${opt:secrets}):MONGO_URI}
  createProduct:
    handler: functions/handlers.createProduct
    events:
      - http:
          path: product/v1/create
          method: post
          cors:
            origins:
              - '*'
            headers:
              - authtoken
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
    environment:
      PRODUCT_TABLE: ${self:custom.ProductItemTable}
      USER_TABLE: ${self:custom.UserItemTable}

  updateProductData:
    handler: functions/handlers.updateProductData
    events:
      - http:
          path: product/v1/update/data/{id}
          method: post
          cors:
            origins:
              - '*'
            headers:
              - authtoken
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
          request:
            parameters:
              paths:
                id: true
    environment:
      PRODUCT_DATA_TABLE: ${self:custom.ProductDataTable}
      USER_TABLE: ${self:custom.UserItemTable}

  getProductBatch:
    handler: functions/handlers.getBatch
    events:
      - http:
          path: product/v1/batch
          method: post
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
    environment:
      PRODUCT_DATA_TABLE: ${self:custom.ProductDataTable}
      PRODUCT_ITEM_TABLE: ${self:custom.ProductItemTable}

  # getProductList:
  #   handler: functions/handlers.getProductList
  #   events:
  #     - http:
  #         path: product/v1/list
  #         method: get
  #         cors:
  #           origins:
  #             - '*'
  #           headers:
  #             - authtoken
  #             - Content-Type
  #             - X-Amz-Date
  #             - Authorization
  #             - X-Api-Key
  #             - X-Amz-Security-Token
  #   environment:
  #     PRODUCT_DATA_TABLE: ${self:custom.ProductDataTable}
  #     PRODUCT_ITEM_TABLE: ${self:custom.ProductItemTable}

  purchase:
    handler: functions/handlers.order
    events:
      - http:
          path: purchase/v1/charge
          method: post
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
    environment:
      ORDER_DATA_TABLE: ${self:custom.OrderDataTable}
      ORDER_ITEM_TABLE: ${self:custom.OrderItemTable}
      PRODUCT_ITEM_TABLE: ${self:custom.ProductItemTable}
      PRODUCT_DATA_TABLE: ${self:custom.ProductDataTable}
      STRIPE_SECRET_KEY: ${file(${opt:secrets}):stripeSecretKey}

  emailAdmin:
    handler: functions/handlers.emailAdmin
    events:
      - stream:
          type: dynamodb
          startingPosition: LATEST
          arn:
            Fn::GetAtt:
              - OrderItemTable
              - StreamArn
    environment:
      ADMIN_EMAIL: ${file(${opt:secrets}):adminEmail}
      ORDER_DATA_TABLE: ${self:custom.OrderDataTable}

  onOrderCreate:
    handler: functions/handlers.onOrderCreate
    events:
       - stream:
          type: dynamodb
          startingPosition: LATEST
          arn:
            Fn::GetAtt:
              - OrderItemTable
              - StreamArn
    environment:
      ORDER_DATA_TABLE: ${self:custom.OrderDataTable}

  getProductData:
    handler: functions/handlers.getProductData
    events:
      - http:
          path: product/v1/data/{id}
          method: get
          cors:
            origins:
              - '*'
            headers:
              - authtoken
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
          request:
            parameters:
              paths:
                id: true
    environment:
      PRODUCT_DATA_TABLE: ${self:custom.ProductDataTable}
      PRODUCT_ITEM_TABLE: ${self:custom.ProductItemTable}

resources:
  Resources:
    UserItemTable: ${file(./resources/User/Item.yml)}
    UserDataTable: ${file(./resources/User/Data.yml)}
    ProductItemTable: ${file(./resources/Product/Item.yml)}
    ProductDataTable: ${file(./resources/Product/Data.yml)}
    OrderItemTable: ${file(./resources/Order/Item.yml)}
    OrderDataTable: ${file(./resources/Order/Data.yml)}
    # S3Bucket:
    #   Type: "AWS::S3::Bucket"
    #   Properties:
    #     BucketName: ${self:service}


    # ProductTable: ${file(./resources/ProductTable.yml)}
    # ChargeTable: ${file(./resources/ChargeTable.yml)}
    # FavoriteTable: ${file(./resources/FavoriteTable.yml)}
    # ProductMediaTable: ${file(./resources/ProductMediaTable.yml)}
    # TaggedProductTable: ${file(./resources/TaggedProductTable.yml)}
    # TagTable: ${file(./resources/TagTable.yml)}
    # UserProfileTable: ${file(./resources/UserProfileTable.yml)}
    # UserTable: ${file(./resources/UserTable.yml)}
