import { keyMirror } from 'Utils';

export default keyMirror({
  LOG_IN: null,
  SET_ERROR: null,
  SET_USER_DATA: null,
  SIGN_UP: null,
  USER_AUTH_SUCCESS: null,
  APP_LOAD: null,
  LOG_OUT: null,
  CLEAR_AUTHENTICATION_DATA: null,
  LOADING: null,
  SET_REDIRECT_PATH: null,
  PRODUCT_LIST_LOADED: null,
  ADD_TO_CART: null,
  ON_CLEAR_FILTERS: null,
  PRODUCT_DATA_LOADED: null,
  REMOVE_FROM_CART: null,
  TOGGLE_FAVORITE: null,
  ON_FILTER_UPDATE: null,
  REPLACE_PRODUCT_LIST: null,
  PURCHASE: null,
  LOAD_FAVORITES: null,
  FAVORITES_LOADED: null,
  SET_LOADING_PAGE: null,
  SET_ORDER_CONFIRMATION: null,
  REPLACE_CART: null,
  LOAD_MORE: null,
  LOAD_MORE_DONE: null,
  PRODUCT_DETAIL_LOADED: null,
  GET_PRODUCT_DETAILS: null,
  ON_NAV_OPEN: null,
  HOME_LOADED: null,
  ON_COLLECTION_SUCCESS: null,
  REQUEST_COLLECTION: null,
});
