branch-defaults:
  develop:
    environment: null
    group_suffix: null
global:
  application_name: archadon
  default_ec2_keyname: null
  default_platform: node.js
  default_region: us-west-2
  profile: eb-cli
  sc: git
