Type: AWS::DynamoDB::Table
Properties:
  TableName: ProductTable-${self:service}-${self:custom.env}
  KeySchema:
    -
      AttributeName: ID
      KeyType: HASH
    -
      AttributeName: Price
      KeyType: RANGE
  AttributeDefinitions:
    -
      AttributeName: ID
      AttributeType: S
    -
      AttributeName: Price
      AttributeType: N
  ProvisionedThroughput:
    ReadCapacityUnits: 5
    WriteCapacityUnits: 5
  StreamSpecification:
    StreamViewType: KEYS_ONLY
