Type: AWS::DynamoDB::Table
Properties:
  TableName: ProductTable-${self:service}
  KeySchema:
    -
      AttributeName: ItemID
      KeyType: HASH
    -
      AttributeName: Price
      KeyType: RANGE
  AttributeDefinitions:
    -
      AttributeName: ItemID
      AttributeType: S
    -
      AttributeName: Price
      AttributeType: N
  ProvisionedThroughput:
    ReadCapacityUnits: 3
    WriteCapacityUnits: 3
  StreamSpecification:
    StreamViewType: KEYS_ONLY
