module.exports = [
  {
    Name: 'Rug',
    Price: 250.32,
    LongDescription: 'This is the long description',
    ShortDescription: 'This is the short description',
    Width: 9,
    Height: 11,
  },
  {
    Name: 'Rug',
    Price: 250.32,
    LongDescription: 'This is the long description',
    ShortDescription: 'This is the short description',
    Width: 9,
    Height: 11,
  },
  {
    Name: 'Rug',
    Price: 250.32,
    LongDescription: 'This is the long description',
    ShortDescription: 'This is the short description',
    Width: 9,
    Height: 11,
  },
  {
    Name: 'Rug',
    Price: 250.32,
    LongDescription: 'This is the long description',
    ShortDescription: 'This is the short description',
    Width: 9,
    Height: 11,
  },
  {
    Name: 'Rug',
    Price: 250.32,
    LongDescription: 'This is the long description',
    ShortDescription: 'This is the short description',
    Width: 9,
    Height: 11,
  },
  {
    Name: 'Rug',
    Price: 250.32,
    LongDescription: 'This is the long description',
    ShortDescription: 'This is the short description',
    Width: 9,
    Height: 11,
  },
  {
    Name: 'Rug',
    Price: 250.32,
    LongDescription: 'This is the long description',
    ShortDescription: 'This is the short description',
    Width: 9,
    Height: 11,
  },
  {
    Name: 'Rug',
    Price: 250.32,
    LongDescription: 'This is the long description',
    ShortDescription: 'This is the short description',
    Width: 9,
    Height: 11,
  },
  {
    Name: 'Rug',
    Price: 250.32,
    LongDescription: 'This is the long description',
    ShortDescription: 'This is the short description',
    Width: 9,
    Height: 11,
  }, {
    Name: 'Rug',
    Price: 250.32,
    LongDescription: 'This is the long description',
    ShortDescription: 'This is the short description',
    Width: 9,
    Height: 11,
  },
  {
    Name: 'Rug',
    Price: 250.32,
    LongDescription: 'This is the long description',
    ShortDescription: 'This is the short description',
    Width: 9,
    Height: 11,
  },
  {
    Name: 'Rug',
    Price: 250.32,
    LongDescription: 'This is the long description',
    ShortDescription: 'This is the short description',
    Width: 9,
    Height: 11,
  }, {
    Name: 'Rug',
    Price: 250.32,
    LongDescription: 'This is the long description',
    ShortDescription: 'This is the short description',
    Width: 9,
    Height: 11,
  },
  {
    Name: 'Rug',
    Price: 250.32,
    LongDescription: 'This is the long description',
    ShortDescription: 'This is the short description',
    Width: 9,
    Height: 11,
  },
  {
    Name: 'Rug',
    Price: 250.32,
    LongDescription: 'This is the long description',
    ShortDescription: 'This is the short description',
    Width: 9,
    Height: 11,
  }, {
    Name: 'Rug',
    Price: 250.32,
    LongDescription: 'This is the long description',
    ShortDescription: 'This is the short description',
    Width: 9,
    Height: 11,
  },
  {
    Name: 'Rug',
    Price: 250.32,
    LongDescription: 'This is the long description',
    ShortDescription: 'This is the short description',
    Width: 9,
    Height: 11,
  },
  {
    Name: 'Rug',
    Price: 250.32,
    LongDescription: 'This is the long description',
    ShortDescription: 'This is the short description',
    Width: 9,
    Height: 11,
  }, {
    Name: 'Rug',
    Price: 250.32,
    LongDescription: 'This is the long description',
    ShortDescription: 'This is the short description',
    Width: 9,
    Height: 11,
  },
  {
    Name: 'Rug',
    Price: 250.32,
    LongDescription: 'This is the long description',
    ShortDescription: 'This is the short description',
    Width: 9,
    Height: 11,
  },
  {
    Name: 'Rug',
    Price: 250.32,
    LongDescription: 'This is the long description',
    ShortDescription: 'This is the short description',
    Width: 9,
    Height: 11,
  }, {
    Name: 'Rug',
    Price: 250.32,
    LongDescription: 'This is the long description',
    ShortDescription: 'This is the short description',
    Width: 9,
    Height: 11,
  },
  {
    Name: 'Rug',
    Price: 250.32,
    LongDescription: 'This is the long description',
    ShortDescription: 'This is the short description',
    Width: 9,
    Height: 11,
  },
  {
    Name: 'Rug',
    Price: 250.32,
    LongDescription: 'This is the long description',
    ShortDescription: 'This is the short description',
    Width: 9,
    Height: 11,
  }, {
    Name: 'Rug',
    Price: 250.32,
    LongDescription: 'This is the long description',
    ShortDescription: 'This is the short description',
    Width: 9,
    Height: 11,
  },
  {
    Name: 'Rug',
    Price: 250.32,
    LongDescription: 'This is the long description',
    ShortDescription: 'This is the short description',
    Width: 9,
    Height: 11,
  },
  {
    Name: 'Rug',
    Price: 250.32,
    LongDescription: 'This is the long description',
    ShortDescription: 'This is the short description',
    Width: 9,
    Height: 11,
  }, {
    Name: 'Rug',
    Price: 250.32,
    LongDescription: 'This is the long description',
    ShortDescription: 'This is the short description',
    Width: 9,
    Height: 11,
  },
  {
    Name: 'Rug',
    Price: 250.32,
    LongDescription: 'This is the long description',
    ShortDescription: 'This is the short description',
    Width: 9,
    Height: 11,
  },
  {
    Name: 'Rug',
    Price: 250.32,
    LongDescription: 'This is the long description',
    ShortDescription: 'This is the short description',
    Width: 9,
    Height: 11,
  }, {
    Name: 'Rug',
    Price: 250.32,
    LongDescription: 'This is the long description',
    ShortDescription: 'This is the short description',
    Width: 9,
    Height: 11,
  },
  {
    Name: 'Rug',
    Price: 250.32,
    LongDescription: 'This is the long description',
    ShortDescription: 'This is the short description',
    Width: 9,
    Height: 11,
  },
  {
    Name: 'Rug',
    Price: 250.32,
    LongDescription: 'This is the long description',
    ShortDescription: 'This is the short description',
    Width: 9,
    Height: 11,
  }, {
    Name: 'Rug',
    Price: 250.32,
    LongDescription: 'This is the long description',
    ShortDescription: 'This is the short description',
    Width: 9,
    Height: 11,
  },
  {
    Name: 'Rug',
    Price: 250.32,
    LongDescription: 'This is the long description',
    ShortDescription: 'This is the short description',
    Width: 9,
    Height: 11,
  },
  {
    Name: 'Rug',
    Price: 250.32,
    LongDescription: 'This is the long description',
    ShortDescription: 'This is the short description',
    Width: 9,
    Height: 11,
  }, {
    Name: 'Rug',
    Price: 250.32,
    LongDescription: 'This is the long description',
    ShortDescription: 'This is the short description',
    Width: 9,
    Height: 11,
  },
  {
    Name: 'Rug',
    Price: 250.32,
    LongDescription: 'This is the long description',
    ShortDescription: 'This is the short description',
    Width: 9,
    Height: 11,
  },
  {
    Name: 'Rug',
    Price: 250.32,
    LongDescription: 'This is the long description',
    ShortDescription: 'This is the short description',
    Width: 9,
    Height: 11,
  },
];
